### ISSUE TITLE
KYS file format

### ISSUE THREAD

**Issue by tugstugi** [ccvv804/hinahana#1]
Hi @ccvv804

do you have any information regarding KYS file format?

Greetings
tugstugi

**Comment by ccvv804** [comment]
I don't know what KYS is. Do you have a KYS file?

**Comment by tugstugi** [comment]
Hi ccvv804, here is a PK2 file containing a sqlite database and KYS files: https://www.dropbox.com/s/ndeyw3mzg9kwvka/KYSNS211220.PK2?dl=0

KYS files can be extracted from PK2 with:
```
import struct
f = open('filePK2', 'rb')
header = f.read(28)
print("header?")
print(header.decode("utf8"), header)
file_count = struct.unpack('<l', f.read(4))[0]
print("file count:", file_count)
file_sizes = []
for i in range(file_count):
    name = f.read(16*32 - 4)
    file_size = struct.unpack('<l', f.read(4))[0]
    print("%i th file size: %i" % (i, file_size))
    file_sizes.append(file_size)
for i, file_size in enumerate(file_sizes):
    bytes = f.read(file_size)
    open('%i.KYS' % i, 'wb').write(bytes)
```

**Comment by ccvv804** [comment]
It appears to be a bundle of encrypted MIDI files used by DVD player-grade karaoke. DVD player-grade karaoke is completely different from Korean domestic karaoke (HANA, SKY, KMS), so I can't help you.

**Comment by tugstugi** [comment]
Thanks for the response. I have also KY3-*.bin with same songs. Any idea how to decrypt them? :)

Greetings
tugstugi

**Comment by ccvv804** [comment]
Are you talking about KY3 files and HANB encryption?

**Comment by tugstugi** [comment]
> Are you talking about KY3 files and HANB encryption?

Here is the file https://www.dropbox.com/s/eb5yqboccboegqb/KY3-MON2112.bin?dl=0
It is for KumYoung, so probably KY3 file?

**Comment by ccvv804** [comment]
Sorry, not the KY3 file I thought it was.
